// Generated by scripts/gen-db-types.mjs — do not edit. Regenerate with `pnpm db:types`.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      audit_log: {
        Row: {
          id: number
          tablename: string
          rowid: string
          op: string
          olddata: Json | null
          newdata: Json | null
          actor: string | null
          at: string
        }
        Insert: {
          id?: never
          tablename: string
          rowid: string
          op: string
          olddata?: Json | null
          newdata?: Json | null
          actor?: string | null
          at?: string
        }
        Update: {
          id?: never
          tablename?: string
          rowid?: string
          op?: string
          olddata?: Json | null
          newdata?: Json | null
          actor?: string | null
          at?: string
        }
        Relationships: []
      }
      bank_transactions: {
        Row: {
          id: number
          bankaccount: string
          postedon: string
          amount: number
          description: string
          expid: number | null
          fndsid: number | null
          importedat: string
        }
        Insert: {
          id?: never
          bankaccount: string
          postedon: string
          amount: number
          description: string
          expid?: number | null
          fndsid?: number | null
          importedat?: string
        }
        Update: {
          id?: never
          bankaccount?: string
          postedon?: string
          amount?: number
          description?: string
          expid?: number | null
          fndsid?: number | null
          importedat?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          email: string
          role: string
          personid: number | null
          createdat: string
        }
        Insert: {
          id: string
          email: string
          role: string
          personid?: number | null
          createdat?: string
        }
        Update: {
          id?: string
          email?: string
          role?: string
          personid?: number | null
          createdat?: string
        }
        Relationships: []
      }
      tbl_scannedbillandcheck: {
        Row: {
          id_number: number
          check_number: number | null
          check_date: string | null
          description: string | null
          long_description: string | null
          scan_filename: string | null
        }
        Insert: {
          id_number?: number
          check_number?: number | null
          check_date?: string | null
          description?: string | null
          long_description?: string | null
          scan_filename?: string | null
        }
        Update: {
          id_number?: number
          check_number?: number | null
          check_date?: string | null
          description?: string | null
          long_description?: string | null
          scan_filename?: string | null
        }
        Relationships: []
      }
      tblactivity: {
        Row: {
          actid: number
          actcaseid: number
          actdate: string
          actdescription: string
          acthrs: number
          actwho: number | null
          actbilled: boolean
          actbillid: number | null
        }
        Insert: {
          actid?: number
          actcaseid: number
          actdate: string
          actdescription: string
          acthrs: number
          actwho?: number | null
          actbilled?: boolean
          actbillid?: number | null
        }
        Update: {
          actid?: number
          actcaseid?: number
          actdate?: string
          actdescription?: string
          acthrs?: number
          actwho?: number | null
          actbilled?: boolean
          actbillid?: number | null
        }
        Relationships: []
      }
      tblattorney: {
        Row: {
          attyid: number
          attyfirmid: number
          attytitle: string | null
          attyfirstname: string
          attymiddlename: string | null
          attylastname: string
          attysuffix: string | null
          attyesq: boolean | null
          attyphone: string | null
          attyemail: string | null
          attycellphone: string | null
        }
        Insert: {
          attyid?: number
          attyfirmid: number
          attytitle?: string | null
          attyfirstname: string
          attymiddlename?: string | null
          attylastname: string
          attysuffix?: string | null
          attyesq?: boolean | null
          attyphone?: string | null
          attyemail?: string | null
          attycellphone?: string | null
        }
        Update: {
          attyid?: number
          attyfirmid?: number
          attytitle?: string | null
          attyfirstname?: string
          attymiddlename?: string | null
          attylastname?: string
          attysuffix?: string | null
          attyesq?: boolean | null
          attyphone?: string | null
          attyemail?: string | null
          attycellphone?: string | null
        }
        Relationships: []
      }
      tblbillingnames: {
        Row: {
          personid: number
          initials: string
          billingfactor: number
        }
        Insert: {
          personid?: number
          initials: string
          billingfactor: number
        }
        Update: {
          personid?: number
          initials?: string
          billingfactor?: number
        }
        Relationships: []
      }
      tblbilllines: {
        Row: {
          lineid: number
          billid: number
          lineno: number
          kind: string
          linedate: string | null
          description: string
          personid: number | null
          hours: number | null
          rate: number | null
          amount: number
        }
        Insert: {
          lineid?: never
          billid: number
          lineno: number
          kind: string
          linedate?: string | null
          description: string
          personid?: number | null
          hours?: number | null
          rate?: number | null
          amount: number
        }
        Update: {
          lineid?: never
          billid?: number
          lineno?: number
          kind?: string
          linedate?: string | null
          description?: string
          personid?: number | null
          hours?: number | null
          rate?: number | null
          amount?: number
        }
        Relationships: []
      }
      tblbills: {
        Row: {
          billid: number
          billcaseid: number
          billdate: string
          billhours: number
          billbalance: number
          billreports: number | null
          billfilename: string | null
          billnotice: string
          billpaiddate: string | null
          billestimate: boolean | null
          billpriority: number | null
          billcomments: string | null
          billsecondnoticedate: string | null
          billfinalnoticedate: string | null
          billtype: string | null
          supersedesbillid: number | null
          billfinalizedat: string | null
          billpdfpath: string | null
          billsentat: string | null
          billsentto: string | null
        }
        Insert: {
          billid?: number
          billcaseid: number
          billdate: string
          billhours: number
          billbalance: number
          billreports?: number | null
          billfilename?: string | null
          billnotice: string
          billpaiddate?: string | null
          billestimate?: boolean | null
          billpriority?: number | null
          billcomments?: string | null
          billsecondnoticedate?: string | null
          billfinalnoticedate?: string | null
          billtype?: string | null
          supersedesbillid?: number | null
          billfinalizedat?: string | null
          billpdfpath?: string | null
          billsentat?: string | null
          billsentto?: string | null
        }
        Update: {
          billid?: number
          billcaseid?: number
          billdate?: string
          billhours?: number
          billbalance?: number
          billreports?: number | null
          billfilename?: string | null
          billnotice?: string
          billpaiddate?: string | null
          billestimate?: boolean | null
          billpriority?: number | null
          billcomments?: string | null
          billsecondnoticedate?: string | null
          billfinalnoticedate?: string | null
          billtype?: string | null
          supersedesbillid?: number | null
          billfinalizedat?: string | null
          billpdfpath?: string | null
          billsentat?: string | null
          billsentto?: string | null
        }
        Relationships: []
      }
      tblbranches: {
        Row: {
          branch: string
        }
        Insert: {
          branch: string
        }
        Update: {
          branch?: string
        }
        Relationships: []
      }
      tblcase: {
        Row: {
          caseid: number
          caseatty: number
          casetitle: string
          casecaption: string | null
          casesubject: string | null
          caseclient: number
          tabranch: string
          status: string
          casenotes: string | null
          casestartdate: string
          caseenddate: string | null
          casestatpriority: string | null
          casestatbriefdescription: string | null
          casestatdescription: string | null
          casestatpointman: string | null
          casestatduedate: string | null
          casestatwaitingfor: string | null
          casestatlastupdated: string | null
          caseinquiry: number | null
          caseattyreference: string | null
          casestatsubpriority: number | null
          casestatduedatedescription: string | null
          numunpaidbills: number | null
          numunapprovedsa: number | null
          otherexperts: string | null
          numscannedfeeschedule: number | null
          billingalert: boolean
          billingcc: string | null
          casestatharddeadline: boolean | null
        }
        Insert: {
          caseid?: number
          caseatty: number
          casetitle: string
          casecaption?: string | null
          casesubject?: string | null
          caseclient: number
          tabranch: string
          status: string
          casenotes?: string | null
          casestartdate: string
          caseenddate?: string | null
          casestatpriority?: string | null
          casestatbriefdescription?: string | null
          casestatdescription?: string | null
          casestatpointman?: string | null
          casestatduedate?: string | null
          casestatwaitingfor?: string | null
          casestatlastupdated?: string | null
          caseinquiry?: number | null
          caseattyreference?: string | null
          casestatsubpriority?: number | null
          casestatduedatedescription?: string | null
          numunpaidbills?: number | null
          numunapprovedsa?: number | null
          otherexperts?: string | null
          numscannedfeeschedule?: number | null
          billingalert?: boolean
          billingcc?: string | null
          casestatharddeadline?: boolean | null
        }
        Update: {
          caseid?: number
          caseatty?: number
          casetitle?: string
          casecaption?: string | null
          casesubject?: string | null
          caseclient?: number
          tabranch?: string
          status?: string
          casenotes?: string | null
          casestartdate?: string
          caseenddate?: string | null
          casestatpriority?: string | null
          casestatbriefdescription?: string | null
          casestatdescription?: string | null
          casestatpointman?: string | null
          casestatduedate?: string | null
          casestatwaitingfor?: string | null
          casestatlastupdated?: string | null
          caseinquiry?: number | null
          caseattyreference?: string | null
          casestatsubpriority?: number | null
          casestatduedatedescription?: string | null
          numunpaidbills?: number | null
          numunapprovedsa?: number | null
          otherexperts?: string | null
          numscannedfeeschedule?: number | null
          billingalert?: boolean
          billingcc?: string | null
          casestatharddeadline?: boolean | null
        }
        Relationships: []
      }
      tblcasepriority: {
        Row: {
          priority: string
        }
        Insert: {
          priority: string
        }
        Update: {
          priority?: string
        }
        Relationships: []
      }
      tblcaseresult: {
        Row: {
          rsltid: number
          rsltcaseid: number
          rsltdate: string | null
          rslttype: string | null
          rsltsatisfaction: string | null
        }
        Insert: {
          rsltid?: number
          rsltcaseid: number
          rsltdate?: string | null
          rslttype?: string | null
          rsltsatisfaction?: string | null
        }
        Update: {
          rsltid?: number
          rsltcaseid?: number
          rsltdate?: string | null
          rslttype?: string | null
          rsltsatisfaction?: string | null
        }
        Relationships: []
      }
      tblcasestatus: {
        Row: {
          casestatus: string
        }
        Insert: {
          casestatus: string
        }
        Update: {
          casestatus?: string
        }
        Relationships: []
      }
      tblcasewaitingfor: {
        Row: {
          waitingfor: string
        }
        Insert: {
          waitingfor: string
        }
        Update: {
          waitingfor?: string
        }
        Relationships: []
      }
      tblclient: {
        Row: {
          clientid: number
          clienttitle: string | null
          clientfirstname: string | null
          clientlastname: string | null
          clientphone: string | null
          clientnotes: string | null
        }
        Insert: {
          clientid?: number
          clienttitle?: string | null
          clientfirstname?: string | null
          clientlastname?: string | null
          clientphone?: string | null
          clientnotes?: string | null
        }
        Update: {
          clientid?: number
          clienttitle?: string | null
          clientfirstname?: string | null
          clientlastname?: string | null
          clientphone?: string | null
          clientnotes?: string | null
        }
        Relationships: []
      }
      tblexpenses: {
        Row: {
          expid: number
          expcaseid: number | null
          expbillid: number | null
          expdate: string
          expdscr: string
          expchecknum: number
          exptype: number | null
          expbranch: string | null
          expamount: number
          expreason: string | null
          expinit: number | null
          expclearedbank: boolean | null
          expdatecleared: string | null
          expbankaccount: string | null
          expclearingnotes: string | null
          exp_scanned_check_number: number | null
          exp_notcountedinprofit: number | null
        }
        Insert: {
          expid?: number
          expcaseid?: number | null
          expbillid?: number | null
          expdate: string
          expdscr: string
          expchecknum: number
          exptype?: number | null
          expbranch?: string | null
          expamount: number
          expreason?: string | null
          expinit?: number | null
          expclearedbank?: boolean | null
          expdatecleared?: string | null
          expbankaccount?: string | null
          expclearingnotes?: string | null
          exp_scanned_check_number?: number | null
          exp_notcountedinprofit?: number | null
        }
        Update: {
          expid?: number
          expcaseid?: number | null
          expbillid?: number | null
          expdate?: string
          expdscr?: string
          expchecknum?: number
          exptype?: number | null
          expbranch?: string | null
          expamount?: number
          expreason?: string | null
          expinit?: number | null
          expclearedbank?: boolean | null
          expdatecleared?: string | null
          expbankaccount?: string | null
          expclearingnotes?: string | null
          exp_scanned_check_number?: number | null
          exp_notcountedinprofit?: number | null
        }
        Relationships: []
      }
      tblexptype: {
        Row: {
          exptypeid: number
          exptype: string
          active: boolean | null
        }
        Insert: {
          exptypeid?: number
          exptype: string
          active?: boolean | null
        }
        Update: {
          exptypeid?: number
          exptype?: string
          active?: boolean | null
        }
        Relationships: []
      }
      tblfirm: {
        Row: {
          frmid: number
          frmname: string
          frmaddress1: string | null
          frmaddress2: string | null
          frmcity: string | null
          frmstate: string | null
          frmzip: string | null
          frmphone: string | null
          frmfax: string | null
          frmemail: string | null
          frmpracticetype: string | null
          frmsize: string | null
          frmactive: string
        }
        Insert: {
          frmid?: number
          frmname: string
          frmaddress1?: string | null
          frmaddress2?: string | null
          frmcity?: string | null
          frmstate?: string | null
          frmzip?: string | null
          frmphone?: string | null
          frmfax?: string | null
          frmemail?: string | null
          frmpracticetype?: string | null
          frmsize?: string | null
          frmactive: string
        }
        Update: {
          frmid?: number
          frmname?: string
          frmaddress1?: string | null
          frmaddress2?: string | null
          frmcity?: string | null
          frmstate?: string | null
          frmzip?: string | null
          frmphone?: string | null
          frmfax?: string | null
          frmemail?: string | null
          frmpracticetype?: string | null
          frmsize?: string | null
          frmactive?: string
        }
        Relationships: []
      }
      tblfundsrcvd: {
        Row: {
          fndsid: number
          fndscaseid: number | null
          fndsdate: string
          fndspmt: number
          fndspayee: string | null
          fndssource: string | null
          fndsdesc: string | null
          fndsbranch: string
          fndssafilename: string | null
          fndsbillfilename: string | null
          fndscomment: string | null
          fndstype: string | null
          fndsclearedbank: boolean | null
          fndsdatecleared: string | null
          fndsbankaccount: string | null
          fndsclearingnotes: string | null
          fndsbillid: number | null
        }
        Insert: {
          fndsid?: number
          fndscaseid?: number | null
          fndsdate: string
          fndspmt: number
          fndspayee?: string | null
          fndssource?: string | null
          fndsdesc?: string | null
          fndsbranch: string
          fndssafilename?: string | null
          fndsbillfilename?: string | null
          fndscomment?: string | null
          fndstype?: string | null
          fndsclearedbank?: boolean | null
          fndsdatecleared?: string | null
          fndsbankaccount?: string | null
          fndsclearingnotes?: string | null
          fndsbillid?: number | null
        }
        Update: {
          fndsid?: number
          fndscaseid?: number | null
          fndsdate?: string
          fndspmt?: number
          fndspayee?: string | null
          fndssource?: string | null
          fndsdesc?: string | null
          fndsbranch?: string
          fndssafilename?: string | null
          fndsbillfilename?: string | null
          fndscomment?: string | null
          fndstype?: string | null
          fndsclearedbank?: boolean | null
          fndsdatecleared?: string | null
          fndsbankaccount?: string | null
          fndsclearingnotes?: string | null
          fndsbillid?: number | null
        }
        Relationships: []
      }
      tblinquiry: {
        Row: {
          id: number
          inqdate: string
          inqtime: string | null
          inqattyid: number | null
          inqsubject: string | null
          inqlocation: string | null
          tabranch: string | null
          inqrefferredby: string | null
          inqresultingcase: number | null
          inqcallertitle: string | null
          inqcallername: string | null
          inqattyname: string | null
          inqfirm: string | null
          inqfirmlocation: string | null
          inqaccidentlocation: string | null
          inqdescription: string | null
          inqhowheardaboutus: string | null
          inqclient: string | null
          inqphonenumber: string | null
          inqaltphonenumber: string | null
          inqfaxnumber: string | null
          inqemail: string | null
          inqpreviouscase: string | null
          inqreceptionist: string | null
          inqengineer: string | null
          inqcaption: string | null
          sentbranch: string | null
          sentfee: boolean | null
          sentchecklist: boolean | null
          sentllb: boolean | null
          sentkjs: boolean | null
          sentiuo: boolean | null
          sentiuobio: boolean | null
          sentoren: boolean | null
          sentlarry: boolean | null
          sentcoppolino: boolean | null
          sentother1: boolean | null
          sentother2: boolean | null
          sentother1name: string | null
          sentother2name: string | null
          sentinfo1: string | null
          sentinfo2: string | null
          sentinfo3: string | null
        }
        Insert: {
          id?: number
          inqdate: string
          inqtime?: string | null
          inqattyid?: number | null
          inqsubject?: string | null
          inqlocation?: string | null
          tabranch?: string | null
          inqrefferredby?: string | null
          inqresultingcase?: number | null
          inqcallertitle?: string | null
          inqcallername?: string | null
          inqattyname?: string | null
          inqfirm?: string | null
          inqfirmlocation?: string | null
          inqaccidentlocation?: string | null
          inqdescription?: string | null
          inqhowheardaboutus?: string | null
          inqclient?: string | null
          inqphonenumber?: string | null
          inqaltphonenumber?: string | null
          inqfaxnumber?: string | null
          inqemail?: string | null
          inqpreviouscase?: string | null
          inqreceptionist?: string | null
          inqengineer?: string | null
          inqcaption?: string | null
          sentbranch?: string | null
          sentfee?: boolean | null
          sentchecklist?: boolean | null
          sentllb?: boolean | null
          sentkjs?: boolean | null
          sentiuo?: boolean | null
          sentiuobio?: boolean | null
          sentoren?: boolean | null
          sentlarry?: boolean | null
          sentcoppolino?: boolean | null
          sentother1?: boolean | null
          sentother2?: boolean | null
          sentother1name?: string | null
          sentother2name?: string | null
          sentinfo1?: string | null
          sentinfo2?: string | null
          sentinfo3?: string | null
        }
        Update: {
          id?: number
          inqdate?: string
          inqtime?: string | null
          inqattyid?: number | null
          inqsubject?: string | null
          inqlocation?: string | null
          tabranch?: string | null
          inqrefferredby?: string | null
          inqresultingcase?: number | null
          inqcallertitle?: string | null
          inqcallername?: string | null
          inqattyname?: string | null
          inqfirm?: string | null
          inqfirmlocation?: string | null
          inqaccidentlocation?: string | null
          inqdescription?: string | null
          inqhowheardaboutus?: string | null
          inqclient?: string | null
          inqphonenumber?: string | null
          inqaltphonenumber?: string | null
          inqfaxnumber?: string | null
          inqemail?: string | null
          inqpreviouscase?: string | null
          inqreceptionist?: string | null
          inqengineer?: string | null
          inqcaption?: string | null
          sentbranch?: string | null
          sentfee?: boolean | null
          sentchecklist?: boolean | null
          sentllb?: boolean | null
          sentkjs?: boolean | null
          sentiuo?: boolean | null
          sentiuobio?: boolean | null
          sentoren?: boolean | null
          sentlarry?: boolean | null
          sentcoppolino?: boolean | null
          sentother1?: boolean | null
          sentother2?: boolean | null
          sentother1name?: string | null
          sentother2name?: string | null
          sentinfo1?: string | null
          sentinfo2?: string | null
          sentinfo3?: string | null
        }
        Relationships: []
      }
      tblscanneddocument: {
        Row: {
          id: number
          caseid: number | null
          expenseid: number | null
          incomeid: number | null
          inquiryid: number | null
          dateadded: string | null
          type: string | null
          description: string | null
          filename: string | null
          billid: number | null
          servauthid: number | null
        }
        Insert: {
          id?: number
          caseid?: number | null
          expenseid?: number | null
          incomeid?: number | null
          inquiryid?: number | null
          dateadded?: string | null
          type?: string | null
          description?: string | null
          filename?: string | null
          billid?: number | null
          servauthid?: number | null
        }
        Update: {
          id?: number
          caseid?: number | null
          expenseid?: number | null
          incomeid?: number | null
          inquiryid?: number | null
          dateadded?: string | null
          type?: string | null
          description?: string | null
          filename?: string | null
          billid?: number | null
          servauthid?: number | null
        }
        Relationships: []
      }
      tblsrvauth: {
        Row: {
          srvauthid: number
          srvauthcaseid: number
          srvauthdate: string
          srvauthhours: number
          srvauthfile: string | null
          srvauthstatus: string
          srvdateapproved: string | null
          srvadvance: number | null
          srvauthnotes: string | null
        }
        Insert: {
          srvauthid?: number
          srvauthcaseid: number
          srvauthdate: string
          srvauthhours: number
          srvauthfile?: string | null
          srvauthstatus: string
          srvdateapproved?: string | null
          srvadvance?: number | null
          srvauthnotes?: string | null
        }
        Update: {
          srvauthid?: number
          srvauthcaseid?: number
          srvauthdate?: string
          srvauthhours?: number
          srvauthfile?: string | null
          srvauthstatus?: string
          srvdateapproved?: string | null
          srvadvance?: number | null
          srvauthnotes?: string | null
        }
        Relationships: []
      }
      tblstates: {
        Row: {
          state: string
        }
        Insert: {
          state: string
        }
        Update: {
          state?: string
        }
        Relationships: []
      }
    }
    Views: {
      case_search: {
        Row: {
          caseid: number | null
          casetitle: string | null
          casenotes: string | null
          casecaption: string | null
          attyname: string | null
          attyemail: string | null
          attyphone: string | null
          frmname: string | null
          frmphone: string | null
          clientname: string | null
          otherexperts: string | null
        }
        Relationships: []
      }
    }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
