/**
 * Bounced-check reversal (admin only). Once-only guard = the primary key: the reversal row is inserted with the
 * explicit id `fndsid = -original.fndsid` (fndsid is GENERATED BY DEFAULT AS IDENTITY, so explicit values are
 * accepted), so a second insert for the same original fails inside the write statement with 23505 — no prior-select
 * guard, no schema change, no delete. A reversal (negative id) could only be "reversed" into -(-x) = x, which already
 * exists; run* also refuses it explicitly before any write.
 * Order: reversal insert first, then the optional bill reopen — a reopened bill never exists without its reversal.
 * Residual: if the bill write loses a race after the insert, the reversal stands and the bill stays Paid (?reverseerror=billstale).
 * The original funds row is only ever read. The reversal row carries the original's bill link (fndsbillid).
 */
import type { Session } from "../auth/session";
import type { Db } from "../time/entries";
import { firmToday } from "../cases/presets";
import { parseMoney } from "./money";

export class ReverseError extends Error {
  constructor(readonly code: string) {
    super(code);
    this.name = "ReverseError";
  }
}

const MESSAGES: Record<string, string> = {
  forbidden: "Only an admin can reverse a bounced check.",
  notfound: "That funds record no longer exists.",
  reversal: "A reversal can't itself be reversed.",
  reversed: "This check has already been reversed.",
  bill: "Pick a paid bill on this case, or no bill.",
  billstale: "The check was reversed, but the bill changed meanwhile and was not reopened.",
};
export const reverseErrorMessage = (code: string): string => MESSAGES[code] ?? "Reversal failed; nothing was recorded.";

export const BOUNCED = "Bounced";
/** Fixed, parseable comment on every reversal row. */
export const reversalComment = (fndsid: number) => `Reversal of fndsid ${fndsid}`;
/** The reversal row's id for an original — the once-only key. */
export const reversalId = (fndsid: number) => -fndsid;

/** Notice a bounced bill returns to: Final if its final date is set, else 2nd if its second date is set, else 1st. */
export function reopenNotice(b: { billfinalnoticedate: string | null; billsecondnoticedate: string | null }): string {
  if (b.billfinalnoticedate) return "Final";
  if (b.billsecondnoticedate) return "2nd";
  return "1st";
}

/** Exact negation of a positive 2-decimal amount, as a string ("1234567.1" → "-1234567.10"); null if not positive. */
export function negateMoney(v: number | string): string | null {
  const s = parseMoney(String(v));
  return s && !s.startsWith("-") ? `-${s}` : null;
}

type Orig = {
  fndsid: number; fndscaseid: number | null; fndspmt: number | string; fndstype: string | null;
  fndspayee: string | null; fndssource: string | null; fndsdesc: string | null; fndsbranch: string;
  fndssafilename: string | null; fndsbillfilename: string | null; fndsbankaccount: string | null; fndsbillid?: number | null;
};
const ORIG_COLS = "fndsid, fndscaseid, fndspmt, fndstype, fndspayee, fndssource, fndsdesc, fndsbranch, fndssafilename, fndsbillfilename, fndsbankaccount, fndsbillid";

/** A reversal row, by any of its markers — never offered the control, never accepted by run*. */
export const isReversal = (r: Pick<Orig, "fndsid" | "fndspmt" | "fndstype">) => r.fndsid < 0 || r.fndstype === BOUNCED || negateMoney(r.fndspmt) === null;

/** Reopen-select preselect: the row's linked bill when it is among the Paid choices, else "" (No bill). */
export const reopenPreselect = (paid: { billid: number }[], fndsbillid: number | null | undefined): string =>
  fndsbillid != null && paid.some((b) => b.billid === fndsbillid) ? String(fndsbillid) : "";

/** The reversal row for an original, if any (the page uses this to hide the control). */
export async function findReversal(db: Db, fndsid: number): Promise<{ fndsid: number } | null> {
  const { data, error } = await db.from("tblfundsrcvd").select("fndsid").eq("fndsid", reversalId(fndsid)).maybeSingle();
  if (error) throw new Error(`tblfundsrcvd reversal read: ${error.message}`);
  return data ?? null;
}

/** Insert the reversal, then (billid > 0) reopen that Paid bill on the same case. Returns the case id. */
export async function reverseFunds(db: Db, fndsid: number, billid: number, today: string): Promise<number> {
  if (!Number.isSafeInteger(fndsid) || fndsid === 0) throw new ReverseError("notfound");
  if (fndsid < 0) throw new ReverseError("reversal");
  const o = await db.from("tblfundsrcvd").select(ORIG_COLS).eq("fndsid", fndsid).maybeSingle();
  if (o.error) throw new Error(`tblfundsrcvd read: ${o.error.message}`);
  const orig = o.data as Orig | null;
  if (!orig || orig.fndscaseid == null) throw new ReverseError("notfound");
  if (isReversal(orig)) throw new ReverseError("reversal");
  const amount = negateMoney(orig.fndspmt)!;

  // Bill pre-check only narrows the residual (bad pick refused before anything is written); the bill write re-guards.
  let bill: { billfinalnoticedate: string | null; billsecondnoticedate: string | null } | null = null;
  if (billid) {
    const b = await db.from("tblbills").select("billid, billfinalnoticedate, billsecondnoticedate")
      .eq("billid", billid).eq("billcaseid", orig.fndscaseid).eq("billnotice", "Paid").maybeSingle();
    if (b.error) throw new Error(`tblbills read: ${b.error.message}`);
    if (!b.data) throw new ReverseError("bill");
    bill = b.data;
  }

  const ins = await db.from("tblfundsrcvd").insert({
    fndsid: reversalId(fndsid),
    fndscaseid: orig.fndscaseid,
    fndsdate: today,
    fndspmt: amount,
    fndstype: BOUNCED,
    fndscomment: reversalComment(fndsid),
    fndspayee: orig.fndspayee, fndssource: orig.fndssource, fndsdesc: orig.fndsdesc, fndsbranch: orig.fndsbranch,
    fndssafilename: orig.fndssafilename, fndsbillfilename: orig.fndsbillfilename, fndsbankaccount: orig.fndsbankaccount,
    fndsbillid: orig.fndsbillid ?? null,
    // The reversal has not cleared the bank yet: cleared fields start fresh rather than copied.
    fndsclearedbank: false, fndsdatecleared: null, fndsclearingnotes: null,
  }).select("fndsid").single();
  if (ins.error) {
    if (ins.error.code === "23505") throw new ReverseError("reversed");
    throw new Error(`tblfundsrcvd reversal insert: ${ins.error.message}`);
  }

  if (bill) {
    // Guard in the write: same bill, same case, still Paid, notice dates still what the rule read.
    let q = db.from("tblbills").update({ billnotice: reopenNotice(bill), billpaiddate: null })
      .eq("billid", billid).eq("billcaseid", orig.fndscaseid).eq("billnotice", "Paid");
    q = bill.billfinalnoticedate ? q.eq("billfinalnoticedate", bill.billfinalnoticedate) : q.is("billfinalnoticedate", null);
    q = bill.billsecondnoticedate ? q.eq("billsecondnoticedate", bill.billsecondnoticedate) : q.is("billsecondnoticedate", null);
    const { data, error } = await q.select("billid");
    if (error) throw new Error(`tblbills reopen: ${error.message}`);
    if (!data || data.length !== 1) throw new ReverseError("billstale");
  }
  return orig.fndscaseid;
}

export type ReverseDeps = {
  session: () => Promise<Session>;
  db: () => Db;
  now: () => Date;
  revalidatePath: (p: string) => void;
  redirect: (url: string) => void;
};

/** /funds/[id] reverse action body. Admin check first (no DB call for staff). Success → ?reversed=<new id>; refusal → ?reverseerror=<code>. */
export async function runReverseFunds(fndsid: number, formData: FormData, deps: ReverseDeps): Promise<void> {
  let code: string | null = null;
  let caseId: number | null = null;
  let billid = 0;
  try {
    const s = await deps.session();
    if (s.role !== "admin") code = "forbidden";
  } catch (e) {
    if (e instanceof Error && e.name === "ForbiddenError") code = "forbidden";
    else throw e; // /login redirect must propagate
  }
  if (!code) {
    const raw = formData.get("bill");
    try {
      if (raw !== null && raw !== "" && !(typeof raw === "string" && /^\d{1,9}$/.test(raw))) throw new ReverseError("bill");
      billid = raw ? Number(raw) : 0;
      caseId = await reverseFunds(deps.db(), fndsid, billid, firmToday(deps.now()));
    } catch (e) {
      if (e instanceof ReverseError) code = e.code;
      else {
        console.error("reverseFunds:", e);
        code = "failed";
      }
    }
  }
  deps.revalidatePath(`/funds/${fndsid}`);
  if (!code || code === "billstale") {
    deps.revalidatePath("/funds");
    deps.revalidatePath(`/funds/${reversalId(fndsid)}`);
    if (billid) { deps.revalidatePath("/bills"); deps.revalidatePath(`/bills/${billid}`); }
    // billstale: reverseFunds threw after the insert, so caseId is unset — the funds list is still revalidated.
    if (caseId != null) deps.revalidatePath(`/cases/${caseId}`);
  }
  deps.redirect(code ? `/funds/${fndsid}?reverseerror=${code}` : `/funds/${fndsid}?reversed=${reversalId(fndsid)}`);
}
