-- 0001_legacy_schema: the 20 SQL Server TechAssoc tables, names lowercased, types decoded from the .bak (see FOUNDATION.md)

create table tblstates (
  state text not null,
  primary key (state)
);

create table tblbranches (
  branch text not null,
  primary key (branch)
);

create table tblcasestatus (
  casestatus text not null,
  primary key (casestatus)
);

create table tblcasepriority (
  priority text not null,
  primary key (priority)
);

create table tblcasewaitingfor (
  waitingfor text not null,
  primary key (waitingfor)
);

create table tblbillingnames (
  personid smallint generated by default as identity not null,
  initials text not null,
  billingfactor numeric(8,3) not null,
  primary key (personid)
);

create table tblexptype (
  exptypeid smallint generated by default as identity not null,
  exptype text not null,
  active boolean not null default false,
  primary key (exptypeid)
);

create table tblfirm (
  frmid integer generated by default as identity not null,
  frmname text not null,
  frmaddress1 text,
  frmaddress2 text,
  frmcity text,
  frmstate text,
  frmzip text,
  frmphone text,
  frmfax text,
  frmemail text,
  frmpracticetype text,
  frmsize text,
  frmactive text not null,
  primary key (frmid)
);

create table tblattorney (
  attyid integer generated by default as identity not null,
  attyfirmid integer not null,
  attytitle text,
  attyfirstname text not null,
  attymiddlename text,
  attylastname text not null,
  attysuffix text,
  attyesq boolean not null default false,
  attyphone text,
  attyemail text,
  attycellphone text,
  primary key (attyid)
);

create table tblclient (
  clientid integer generated by default as identity not null,
  clienttitle text,
  clientfirstname text,
  clientlastname text,
  clientphone text,
  clientnotes text,
  primary key (clientid)
);

create table tblinquiry (
  id integer generated by default as identity not null,
  inqdate date not null,
  inqtime time,
  inqattyid integer,
  inqsubject text,
  inqlocation text,
  tabranch text,
  inqrefferredby text,
  inqresultingcase smallint,
  inqcallertitle text,
  inqcallername text,
  inqattyname text,
  inqfirm text,
  inqfirmlocation text,
  inqaccidentlocation text,
  inqdescription text,
  inqhowheardaboutus text,
  inqclient text,
  inqphonenumber text,
  inqaltphonenumber text,
  inqfaxnumber text,
  inqemail text,
  inqpreviouscase text,
  inqreceptionist text,
  inqengineer text,
  inqcaption text,
  sentbranch text,
  sentfee boolean not null default false,
  sentchecklist boolean not null default false,
  sentllb boolean not null default false,
  sentkjs boolean not null default false,
  sentiuo boolean not null default false,
  sentiuobio boolean not null default false,
  sentoren boolean not null default false,
  sentlarry boolean not null default false,
  sentcoppolino boolean not null default false,
  sentother1 boolean not null default false,
  sentother2 boolean not null default false,
  sentother1name text,
  sentother2name text,
  sentinfo1 text,
  sentinfo2 text,
  sentinfo3 text,
  primary key (id)
);

create table tblcase (
  caseid integer generated by default as identity not null,
  caseatty integer not null,
  casetitle text not null,
  casecaption text,
  casesubject text,
  caseclient integer not null,
  tabranch text not null,
  status text not null,
  casenotes text,
  casestartdate date not null,
  caseenddate date,
  casestatpriority text,
  casestatbriefdescription text,
  casestatdescription text,
  casestatpointman text,
  casestatduedate date,
  casestatwaitingfor text,
  casestatlastupdated timestamptz,
  caseinquiry integer,
  caseattyreference text,
  casestatsubpriority integer,
  casestatduedatedescription text,
  numunpaidbills integer,
  numunapprovedsa integer,
  otherexperts text,
  numscannedfeeschedule integer,
  billingalert boolean not null default false,
  billingcc text,
  casestatharddeadline boolean not null default false,
  casestatusharddeadline boolean not null default false,
  primary key (caseid)
);

create table tblbills (
  billid integer generated by default as identity not null,
  billcaseid integer not null,
  billdate date not null,
  billhours numeric(8,2) not null,
  billbalance numeric(12,2) not null,
  billreports smallint,
  billfilename text,
  billnotice text not null,
  billpaiddate date,
  billestimate boolean not null default false,
  billpriority integer,
  billcomments text,
  billsecondnoticedate date,
  billfinalnoticedate date,
  primary key (billid)
);

create table tblactivity (
  actid integer generated by default as identity not null,
  actcaseid integer not null,
  actdate date not null,
  actdescription text not null,
  acthrs numeric(8,2) not null,
  actwho smallint,
  actbilled boolean not null default false,
  primary key (actid)
);

create table tblexpenses (
  expid integer generated by default as identity not null,
  expcaseid integer,
  expbillid integer,
  expdate date not null,
  expdscr text not null,
  expchecknum integer not null,
  exptype smallint,
  expbranch text,
  expamount numeric(12,2) not null,
  expreason text,
  expinit smallint,
  expclearedbank boolean not null default false,
  expdatecleared date,
  expbankaccount text,
  expclearingnotes text,
  exp_scanned_check_number integer,
  exp_notcountedinprofit numeric(12,2),
  primary key (expid)
);

create table tblfundsrcvd (
  fndsid integer generated by default as identity not null,
  fndscaseid integer,
  fndsdate date not null,
  fndspmt numeric(12,2) not null,
  fndspayee text,
  fndssource text,
  fndsdesc text,
  fndsbranch text not null,
  fndssafilename text,
  fndsbillfilename text,
  fndscomment text,
  fndstype text,
  fndsclearedbank boolean not null default false,
  fndsdatecleared date,
  fndsbankaccount text,
  fndsclearingnotes text,
  primary key (fndsid)
);

create table tblsrvauth (
  srvauthid integer generated by default as identity not null,
  srvauthcaseid integer not null,
  srvauthdate date not null,
  srvauthhours numeric(8,2) not null,
  srvauthfile text,
  srvauthstatus text not null,
  srvdateapproved date,
  srvadvance numeric(12,2),
  srvauthnotes text,
  primary key (srvauthid)
);

create table tblcaseresult (
  rsltid integer generated by default as identity not null,
  rsltcaseid integer not null,
  rsltdate date,
  rslttype text,
  rsltsatisfaction text,
  primary key (rsltid)
);

create table tbl_scannedbillandcheck (
  id_number integer generated by default as identity not null,
  check_number integer,
  check_date date,
  description text,
  long_description text,
  scan_filename text,
  primary key (id_number)
);

create table tblscanneddocument (
  id integer generated by default as identity not null,
  caseid integer,
  expenseid integer,
  incomeid integer,
  inquiryid integer,
  dateadded date,
  type text,
  description text,
  filename text,
  billid integer,
  servauthid integer,
  primary key (id)
);

-- FKs NOT VALID: enforced for new rows, legacy orphans tolerated (migration lane counts them)
alter table tblfirm add constraint tblfirm_frmstate_fkey foreign key (frmstate) references tblstates(state) not valid;
alter table tblattorney add constraint tblattorney_attyfirmid_fkey foreign key (attyfirmid) references tblfirm(frmid) not valid;
alter table tblinquiry add constraint tblinquiry_inqattyid_fkey foreign key (inqattyid) references tblattorney(attyid) not valid;
alter table tblcase add constraint tblcase_caseatty_fkey foreign key (caseatty) references tblattorney(attyid) not valid;
alter table tblcase add constraint tblcase_caseclient_fkey foreign key (caseclient) references tblclient(clientid) not valid;
alter table tblcase add constraint tblcase_tabranch_fkey foreign key (tabranch) references tblbranches(branch) not valid;
alter table tblcase add constraint tblcase_status_fkey foreign key (status) references tblcasestatus(casestatus) not valid;
alter table tblcase add constraint tblcase_casestatpriority_fkey foreign key (casestatpriority) references tblcasepriority(priority) not valid;
alter table tblcase add constraint tblcase_casestatwaitingfor_fkey foreign key (casestatwaitingfor) references tblcasewaitingfor(waitingfor) not valid;
alter table tblcase add constraint tblcase_caseinquiry_fkey foreign key (caseinquiry) references tblinquiry(id) not valid;
alter table tblbills add constraint tblbills_billcaseid_fkey foreign key (billcaseid) references tblcase(caseid) not valid;
alter table tblactivity add constraint tblactivity_actcaseid_fkey foreign key (actcaseid) references tblcase(caseid) not valid;
alter table tblactivity add constraint tblactivity_actwho_fkey foreign key (actwho) references tblbillingnames(personid) not valid;
alter table tblexpenses add constraint tblexpenses_expcaseid_fkey foreign key (expcaseid) references tblcase(caseid) not valid;
alter table tblexpenses add constraint tblexpenses_expbillid_fkey foreign key (expbillid) references tblbills(billid) not valid;
alter table tblexpenses add constraint tblexpenses_exptype_fkey foreign key (exptype) references tblexptype(exptypeid) not valid;
alter table tblexpenses add constraint tblexpenses_expinit_fkey foreign key (expinit) references tblbillingnames(personid) not valid;
alter table tblfundsrcvd add constraint tblfundsrcvd_fndscaseid_fkey foreign key (fndscaseid) references tblcase(caseid) not valid;
alter table tblsrvauth add constraint tblsrvauth_srvauthcaseid_fkey foreign key (srvauthcaseid) references tblcase(caseid) not valid;
alter table tblcaseresult add constraint tblcaseresult_rsltcaseid_fkey foreign key (rsltcaseid) references tblcase(caseid) not valid;
alter table tblscanneddocument add constraint tblscanneddocument_caseid_fkey foreign key (caseid) references tblcase(caseid) not valid;
alter table tblscanneddocument add constraint tblscanneddocument_expenseid_fkey foreign key (expenseid) references tblexpenses(expid) not valid;
alter table tblscanneddocument add constraint tblscanneddocument_incomeid_fkey foreign key (incomeid) references tblfundsrcvd(fndsid) not valid;
alter table tblscanneddocument add constraint tblscanneddocument_inquiryid_fkey foreign key (inquiryid) references tblinquiry(id) not valid;
alter table tblscanneddocument add constraint tblscanneddocument_billid_fkey foreign key (billid) references tblbills(billid) not valid;
alter table tblscanneddocument add constraint tblscanneddocument_servauthid_fkey foreign key (servauthid) references tblsrvauth(srvauthid) not valid;
